name: test

on:
  push:
    branches-ignore:
      - gh-pages

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup node.js
        uses: actions/setup-node@v1
        with:
          node-version: 17.x
      - name: Test
        run: |
          npm ci
          npm test
        env:
          CI: true
          NODE_ENV: production
